language: node_js

node_js:
  "node"

dist: xenial
os: linux

services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

install:
  - npm install

before_script:
  - psql -c 'create database ci_test;' -U postgres

script:
  - npm run test
  - npm run lint
