language: node_js

node_js:
  "node"

dist: xenial
os: linux

services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

env:
  global:
  - PGPORT=5432

install:
  - npm install

before_script:
  - psql -c 'create database clearn_test;' -U postgres
  - db-migrate up -e test

script:
  - npm run lint
  - npm run test
